language: python
python:
  - "3.7-dev"
install:
  - pip install pipenv
  - pipenv sync -d
script: 'python -m pytest --cov=pyblizzard tests --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'